version: '3'

tasks:
  default:
    cmds:
      - task: build

  dev:
    desc: Run backend + dashboard dev server concurrently
    deps: [dev:backend, dev:dashboard]

  dev:backend:
    dir: cmd/server
    cmds:
      - go run main.go

  dev:dashboard:
    dir: dashboard
    cmds:
      - pnpm dev

  build:backend:
    cmds:
      - mkdir -p dist
      - go build -o dist/iris-server ./cmd/server

  install:js:
    cmds:
      - pnpm install

  build:js:
    cmds:
      - pnpm --filter @bigchill101/iris build
      - pnpm --filter @iris/dashboard build

  build:
    deps: [build:backend, build:js]